"""add_billing_time_to_subscription_instances

Revision ID: 01b1e4501d9e
Revises: 661b68170d99
Create Date: 2025-07-23 09:50:27.937727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b1e4501d9e'
down_revision: Union[str, None] = '661b68170d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_instances', sa.Column('billing_time', sa.DateTime(), nullable=False))
    op.add_column('subscription_instances', sa.Column('replenishment_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_instances', 'replenishment_time')
    op.drop_column('subscription_instances', 'billing_time')
    # ### end Alembic commands ###
