"""add_archived_at_to_subscriptions

Revision ID: 4e222c78c672
Revises: 01b1e4501d9e
Create Date: 2025-07-23 10:19:03.714538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e222c78c672'
down_revision: Union[str, None] = '01b1e4501d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'archived_at')
    # ### end Alembic commands ###
