"""refactor_subscription_models_add_instances

Revision ID: 661b68170d99
Revises: 3c35a0a4c35d
Create Date: 2025-07-23 09:41:30.163518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '661b68170d99'
down_revision: Union[str, None] = '3c35a0a4c35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'PROGRESS', name='statusenum'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_instances_id'), 'subscription_instances', ['id'], unique=False)
    op.drop_column('subscriptions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('status', mysql.ENUM('COMPLETED', 'PROGRESS', collation='utf8_unicode_ci'), nullable=True))
    op.drop_index(op.f('ix_subscription_instances_id'), table_name='subscription_instances')
    op.drop_table('subscription_instances')
    # ### end Alembic commands ###
