"""fix_enum_to_lowercase_again

Revision ID: a5ac11ade763
Revises: c3140cc93ba5
Create Date: 2025-08-01 17:05:12.286685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ac11ade763'
down_revision: Union[str, None] = 'c3140cc93ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Сначала обновляем данные в нижний регистр
    op.execute("UPDATE subscription_instances SET status = 'completed' WHERE status = 'COMPLETED'")
    op.execute("UPDATE subscription_instances SET status = 'progress' WHERE status = 'PROGRESS'")
    
    # Затем обновляем Enum в нижний регистр
    op.execute("ALTER TABLE subscription_instances MODIFY COLUMN status ENUM('completed', 'progress', 'ready') DEFAULT 'progress'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Возвращаем в верхний регистр
    op.execute("UPDATE subscription_instances SET status = 'COMPLETED' WHERE status = 'completed'")
    op.execute("UPDATE subscription_instances SET status = 'PROGRESS' WHERE status = 'progress'")
    op.execute("ALTER TABLE subscription_instances MODIFY COLUMN status ENUM('COMPLETED', 'PROGRESS', 'READY') DEFAULT 'PROGRESS'")
    
    # ### end Alembic commands ###
