"""update_existing_status_values_to_lowercase

Revision ID: c3140cc93ba5
Revises: e66be7ccce92
Create Date: 2025-08-01 16:45:12.286685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3140cc93ba5'
down_revision: Union[str, None] = 'e66be7ccce92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Обновляем существующие значения статусов в нижний регистр
    op.execute("UPDATE subscription_instances SET status = 'completed' WHERE status = 'COMPLETED'")
    op.execute("UPDATE subscription_instances SET status = 'progress' WHERE status = 'PROGRESS'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Возвращаем значения в верхний регистр (если нужно)
    op.execute("UPDATE subscription_instances SET status = 'COMPLETED' WHERE status = 'completed'")
    op.execute("UPDATE subscription_instances SET status = 'PROGRESS' WHERE status = 'progress'")
    
    # ### end Alembic commands ###
