"""add_ready_status_to_enum

Revision ID: e66be7ccce92
Revises: 4e222c78c672
Create Date: 2025-08-01 16:34:23.286685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66be7ccce92'
down_revision: Union[str, None] = '4e222c78c672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Обновляем Enum для статуса подписок в MySQL
    # MySQL требует пересоздания колонки для изменения Enum
    # Используем нижний регистр для соответствия с Python Enum
    op.execute("ALTER TABLE subscription_instances MODIFY COLUMN status ENUM('completed', 'progress', 'ready') DEFAULT 'progress'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Возвращаем Enum к предыдущему состоянию
    op.execute("ALTER TABLE subscription_instances MODIFY COLUMN status ENUM('completed', 'progress') DEFAULT 'progress'")
    
    # ### end Alembic commands ###
